### ISSUE TITLE
messages at start with example

### ISSUE THREAD

**Issue by marcelloh** [roblillack/spot#14]
tableview.m:70:7: warning: 'NSScrollView' may not respond to 'delegate'
tableview.m:70:7: warning: 'delegate' is deprecated: first deprecated in macOS 10.11 - NSFontManager doesn't have any delegate method. This property should not be used. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontManager.h:92:33: note: property 'delegate' is declared deprecated here
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSFontManager.h:92:33: note: 'delegate' has been explicitly marked deprecated here
2024-05-29 21:08:52.534 spotui[4690:85441] applicationDidFinishLaunching

This is displayed when running the example in the readme

On MacOS M1 processor

**Comment by roblillack** [comment]
Fixed now. Thanks for reporting!

**Comment by marcelloh** [comment]
I can't see it yet, I assume it's not in a release?

**Comment by roblillack** [comment]
@marcelloh, that's right, it's only on `main` now, but will land in the next release.

**Comment by marcelloh** [comment]
confirmed... nice job!
