### ISSUE TITLE
Clicking the window close button  - error

### ISSUE THREAD

**Issue by marcelloh** [roblillack/spot#15]
Or unexpected behaviour: the program doesn't close, and I have to do a Crtl-C to really quit it.
(The hello-spot does quit nicely when clicking the "quit" button, so I know it is possible.)

**Comment by marcelloh** [comment]
Still is the case in the 0.3.1. version

**Comment by roblillack** [comment]
Hey @marcelloh, yes that's right. I'll get to this and find a solution.

**Comment by marcelloh** [comment]
I hope you do find a solution, because I really like the project :-)

**Comment by roblillack** [comment]
Fixed now in 0.3.2.
