### ISSUE TITLE
how to change fltk Scheme?

### ISSUE THREAD

**Issue by ystyle** [roblillack/spot#17]
In Linux, the default is base, and the interface looks very old.

**Comment by roblillack** [comment]
Hey @ystyle,

you can call FLTK's [`fltk.SetStyle()`]() function after [`ui.Init()`] in your code:

```go
import (
	"github.com/pwiecz/go-fltk"
	"github.com/roblillack/spot"
	"github.com/roblillack/spot/ui"
)

func main() {
	ui.Init()
	fltk.SetScheme("plastic")

	spot.MountFn(…)

	ui.Run()
}
```

<img width="526" alt="grafik" src="https://github.com/roblillack/spot/assets/37167/3d87b34a-8cca-41db-80b0-e5cbe41866fd">

Hope that helps!

**Comment by ystyle** [comment]
thanks
